name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test_lint:
    permissions: write-all
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.11"] #, "3.10"]
        
    uses: Chaca588/DjangoPipelines/.github/workflows/lint.yml@main
    with:
      python-version: ${{ matrix.python-version }}

      
  Analyze:
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.language }}-${{ github.ref }}
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: ['python']
    uses: Chaca588/DjangoPipelines/.github/workflows/analyzesCodeQL.yml@main


  Zaproxy:
    runs-on: ubuntu-latest
    name: Run server

    steps:
      - uses: actions/checkout@v4

      - name: Run server
        run: |
          python mysite/manage.py runserver &
      
      - uses: Chaca588/DjangoPipelines/.github/actions/zapproxy-action/zapproxy-full.yml@main


  DockerBuildPush:
    permissions: write-all
    needs: [Analyze, Zaproxy, Test_lint]
    strategy:
      matrix:
        python-version: ["3.11"] #, "3.10"]
    uses: Chaca588/DjangoPipelines/.github/workflows/containerPublisher.yml@main
    with:
      REGISTRY: ghcr.io
