name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  testlint:
    permissions: write-all
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.11"] #, "3.10"]
        
    uses: Chaca588/DjangoPipelines/.github/workflows/lint.yml@main

    
    
  Analyze:
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.language }}-${{ github.ref }}
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: ['python']
    uses: Chaca588/DjangoPipelines/.github/workflows/analyzesCodeQL.yml@main

