name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.11"] #, "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Cache da instalação das dependecias para ser mais rapido
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Lint # With flake8
      run: | # exit-zero serve para evitar que o workflow falhe com os erros
        flake8 --config=my-only-config.ini --exit-zero mysite/

    - name: Run Server # O & é essencial se não e runserver não termina 
      run: |
        python3 mysite/manage.py runserver &

    - name: Run ZAP scan
      uses: ./.github/actions/zapproxy-action
      with:
        target: 'http://127.0.0.1:8000'
        report: 'testreport.html'


      

