name: Reusable CodeQL Analyzes
on: 
  workflow_call:
    inputs:
        python-version:
            required: true
            type: string

jobs:
  lint:
    name: Lint-Reusable
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ inputs.python-version }}
            cache: 'pip' # Cache da instalação das dependecias para ser mais rapido
        - name: Install Dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Test Lint # With flake8
          run: | # exit-zero serve para evitar que o workflow falhe com os erros
            flake8 --config=my-only-config.ini --exit-zero mysite/
        